name: CI

on: push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    outputs:
      artifact_filename: ${{ steps.nerves.outputs.artifact_filename }}
    steps:
      - uses: actions/checkout@v4
      - name: Build
        id: nerves
        uses: redwirelabs/build-nerves-system-action@v1
  draft-release:
    runs-on: ubuntu-24.04
    needs: build
    if: github.ref_type == 'tag'
    steps:
      - uses: actions/checkout@v4
      - name: Fetch artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact_filename }}
      - name: Create draft release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release \
            create \
              ${{ github.ref_name }} \
              ${{ needs.build.outputs.artifact_filename }} \
            --title ${{ github.ref_name }} \
            --draft
